import express from 'express';
import { registerHealth } from './routes/health.js';
import { registerUsers } from './routes/users.js';
import { registerProducts } from './routes/products.js';
import { registerOrders } from './routes/orders.js';
import { registerJobs } from './routes/jobs.js';
import { errorHandler } from './middleware/errors.js';
import { requestLog } from './middleware/request-log.js';
export const app = express();
app.disable('x-powered-by');
app.use(express.json({ limit: '32kb' }));
app.use(requestLog);
registerHealth(app);
registerUsers(app);
registerProducts(app);
registerOrders(app);
registerJobs(app);
app.use((req, res) => res.status(404).json({ error: 'Route not found' }));
app.use(errorHandler);
